default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock

development:
  <<: *default
  username: root
  password: root
  database: exchange_diary_development

test:
  <<: *default
  username: root
  password: root
  database: exchange_diary_test

production:
  <<: *default
  database: exchange_diary_production
